name: Coveralls
on:
  push:
    branches:
      - main
jobs:
  coveralls:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: |
          yarn install
      
      - name: Create badges branch
        run: git checkout -b badges

      - name: Unit Tests
        run: |
          yarn cover

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
      