name: Run Jobs in a container
on:
  push:
    branches:
      - main
jobs:
  run-in-container:
    runs-on: ubuntu-latest
    container: node:14-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: |
          yarn install
      - name: Unit Tests
        run: |
          yarn test