on: push
name: Main
jobs:
  lint-and-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    # - name: Lint
    #   uses: CultureHQ/actions-yarn@master
    #   with:
    #     args: lint
    - name: Test
      uses: CultureHQ/actions-yarn@master
      with:
        args: cover