name: Tests
on:
  push:
    branches:
      - main
jobs:
  run-in-container:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: |
          yarn install

      - name: Unit Tests
        run: |
          yarn cover

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
