on: push
name: Main
jobs:
  lint-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    # - name: Lint
    #   uses: CultureHQ/actions-yarn@master
    #   with:
    #     args: lint
    - name: Test
      uses: CultureHQ/actions-yarn@master
      with:
        args: cover